### ISSUE TITLE
Page reload on the production or using npx serve

### ISSUE THREAD

**Issue by akshays-repo** [nebarf/module-federation-react-router-dom#2]
When the app is reloaded at http://localhost:8080/app/page-1 or directly enters the  URL it occurs on 404. the issue occurs only when the app is hosted or run using npx serve, local development doesn't have any issue

**Comment by nebarf** [comment]
> When the app is reloaded at http://localhost:8080/app/page-1 or directly enters the URL it occurs on 404. the issue occurs only when the app is hosted or run using npx serve, local development doesn't have any issue

This is something you have to handle at web server configuration. Since the app makes use of client side routing, you must ensure that the web server serves index.html when receiving incoming requests on subpaths like `/app/page-1`.

Below a minimal configuration for **nginx** that will handle such scenario:

```
server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
```

Of course the configuration depends on the web server you're using to serve static assets produced by application build.

**Comment by nebarf** [comment]
@akshays-repo Please let me know if you need further help/clarifications.
